vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       article:
           uri_prefix: /img
           upload_destination: '%kernel.project_dir%/public/img'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: true
           delete_on_update: true
           delete_on_remove: true
       avatar:
           uri_prefix: /img
           upload_destination: '%kernel.project_dir%/public/img/avatar'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: true
           delete_on_update: true
           delete_on_remove: true
